[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
deny_warnings = true


[profile.gas-optimize]
solc_version = '0.8.23'
optimizer = true
optimizer_runs = 200_000_000
via_ir = true

[profile.gas-optimize.optimizer_details]
inliner = true
deduplicate = true
constantOptimizer = true
yul = true # makes it worse
# orderLiterals = true # makes it worse
# cse = true # makes it worse